export type LoanStatus = 'pending' | 'approved' | 'rejected' | 'active' | 'completed';

export interface Loan {
  id?: string;               // Optional, generated by database
  clientId: string;          // ID of the client
  amount: number;            // Loan amount
  interestRate: number;      // Annual interest rate in percentage
  duration: number;          // Loan duration in months
  status: LoanStatus;
  riskStatus: 'low' | 'medium' | 'high';
  createdAt?: Date;          // Optional, auto-set when creating
  updatedAt?: Date;          // Optional, auto-set when creating/updating
}
